name: 'Terraform'

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Creating VM
      env:
        VM_NAME: ${{ github.event.client_payload.vm_name }}
      run: |
        if [[ "${{ github.event.client_payload.vm_name }}" == "VM1" ]]; then
          echo "inside if"
          echo "${VM_NAME}"
          cd ./VirtualMachine1
          terraform init
          terraform plan -var "vm_name=${VM_NAME}"
        else
          echo "inside else"
        fi